services:
    app:
        image: php:8.2-fpm
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8000:8000"
        networks:
            - laravel

        environment:
            - PHP_EXTENSION_XDEBUG=1
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: news_api
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

volumes:
    dbdata:
        driver: local

networks:
    laravel:
        driver: bridge
